### ISSUE TITLE
change get_gradient

### ISSUE THREAD

**Issue by ascdqz** [MKowal2/ACE_TCAV_Pytorch#1]
Hello
I'm trying to use a custom model on this. For example, I'm trying to use the 28 layer in the image shown below. When I run the code, it gives error that "CUDA out of memory". You said may need to change the get_gradient function. Can you be more specific about that?
Thank you!
![image](https://user-images.githubusercontent.com/65437325/209232963-a6cc3a25-fd71-4038-8c7a-bd82fbf6eab5.png)
![image](https://user-images.githubusercontent.com/65437325/209232995-0da15698-9b93-40fe-b9c2-dc2a3e18165c.png)
![image](https://user-images.githubusercontent.com/65437325/209233298-121e5f00-ac87-41c6-83e4-59280f0ed0db.png)

**Comment by MKowal2** [comment]
There are some preset batch sizes throughout ace.py, you might want to try changing those. Alternatively, you might need to adjust the function here: https://github.com/MKowal2/ACE_TCAV_Pytorch/blob/main/ace.py#L634 which has some specific layers according to the torch hub models (e.g., the final layer is called 'fc'). I have tried with ResNet101 and other big networks, so there shouldn't be an issue in terms of tensor size. Hope this helps!

**Comment by ascdqz** [comment]
Hello
I had another error when running ACE. I think the error below might mean the input image is empty somewhere? I think I correctly set the source folder as follows. And the SAVE_DIR after running the code will be all empty except the a folder under concepts ("image" folder) that contains all of my target class images reshaped.
Thank you!
![image](https://user-images.githubusercontent.com/65437325/211159769-93050425-cda0-4b66-8198-1656d571e104.png)
![image](https://user-images.githubusercontent.com/65437325/211159868-7ca9ab01-67c5-497d-a3d2-23467bf28b54.png)
![image](https://user-images.githubusercontent.com/65437325/211160510-087af487-4e4e-491d-afe4-ec1650e89a0c.png)
